org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.defaults.buildfeatures.resvalues=true
android.dependency.useConstraints=true
android.enableAppCompileTimeRClass=false
android.newDsl=false
android.r8.optimizedResourceShrinking=false
android.r8.strictFullModeForKeepRules=false
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.uniquePackageNames=false
android.usesSdkInManifest.disallowed=false
unityStreamingAssets=.json
unityTemplateVersion=22
unityProjectPath=C:/Users/Ahmet KARAASLAN/Desktop/Unity-Projeler/LabX
unity.projectPath=C:/Users/Ahmet KARAASLAN/Desktop/Unity-Projeler/LabX
unity.debugSymbolLevel=none
unity.buildToolsVersion=36.0.0
unity.minSdkVersion=25
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.UnityTechnologies.com.unity.template.urpblank
unity.abiFilters=arm64-v8a
unity.versionCode=1
unity.versionName=0.1.0
unity.namespace=com.UnityTechnologies.com.unity.template.urpblank
unity.agpVersion=8.10.0
unity.androidSdkPath=C:/Program Files/Unity/Hub/Editor/6000.4.0f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=C:/Program Files/Unity/Hub/Editor/6000.4.0f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=C:/Program Files/Unity/Hub/Editor/6000.4.0f1/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never
